- name: Provision login node
  hosts: pve
  become: true
  vars:
    pve_host: localhost

  tasks:
    - include_tasks: tasks/setup_proxmox_api.yml
    - include_tasks: tasks/copy_bos_image.yml

    - name: Copy login BOS image
      ansible.builtin.copy:
        src: /var/lib/vz/template/bos.{{item}}.qcow2
        dest: "/var/lib/vz/template/bos.{{item}}.{{login_disk_size}}.qcow2"
        force: false
        remote_src: true
      loop: [x86_64, aarch64]

    - name: Resize login image
      ansible.builtin.shell: "qemu-img resize bos.{{item}}.{{login_disk_size}}.qcow2 {{login_disk_size}}"
      args:
        chdir: /var/lib/vz/template/
      loop: [x86_64, aarch64]

    - include_tasks: tasks/pve_create_vm.yml
      vars:
        vm_name: "login-{{arch_to_dns_map[item]}}.{{domain}}"
        vm_cores: "{{login_ncores}}"
        vm_mem_gb: "{{login_mem_gb}}"
        vm_sshkeys: "{{login_sshkeys | regex_replace('\\\\n', '\n')}}"
        vm_user: "root"
        vm_password: "{{login_password}}"
        vm_ip: "{{login_ip_from_arch_map[item]}}"
        vm_nameservers: "{{router_ip}}"
        vm_ipconfig:
          ipconfig0: "gw={{router_ip}},ip={{login_ip_from_arch_map[item]}}/24"
        vm_net:
          net0: "virtio,bridge=vmbr1"
        vm_scsi:
          scsi0: "{{storage_pool}}:0,import-from=/var/lib/vz/template/bos.{{item}}.{{login_disk_size}}.qcow2,format=qcow2,cache=none,ssd=1,discard=on"
      loop: [x86_64, aarch64]

    - name: Patch up aarch64 login nodes
      ansible.builtin.script:
        cmd: "scripts/patch-pve-aarch64.sh login-{{arch_to_dns_map['aarch64']}}.{{domain}}"

    - include_tasks: tasks/pve_vm_state.yml
      vars:
        {
          vm_name: "login-{{arch_to_dns_map[item]}}.{{domain}}",
          vm_state: started,
        }
      loop: [x86_64, aarch64]

    - include_tasks: tasks/delete_image_templates.yml
