- name: Define expected SSH host key types
  set_fact:
    ssh_host_key_suffixes:
      - "ecdsa_key"
      - "ecdsa_key.pub"
      - "ed25519_key"
      - "ed25519_key.pub"
      - "rsa_key"
      - "rsa_key.pub"

- name: Check if backup keys exist locally
  ansible.builtin.stat:
    path: "{{host_backup_directory}}/ssh_host_{{item}}"
  become: false
  delegate_to: localhost
  loop: "{{ssh_host_key_suffixes}}"
  register: backup_keys_stat

- name: Overwrite remote keys with local backup if they exist
  ansible.builtin.copy:
    src: "{{host_backup_directory}}/ssh_host_{{item}}"
    dest: "/etc/ssh/ssh_host_{{item}}"
    owner: root
    group: root
    mode: "0600"
  loop: "{{backup_keys_stat.results | selectattr('stat.exists', 'eq', True) | map(attribute='item') | list}}"
  when: item is defined

- name: Backup SSH host keys from remote to local
  ansible.builtin.fetch:
    flat: true
    src: "/etc/ssh/ssh_host_{{item}}"
    dest: "{{host_backup_directory}}/ssh_host_{{item}}"
  loop: "{{ssh_host_key_suffixes}}"
